/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/woman.gltf 
*/

import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import { useAnimation } from "../context/CharacterAnimation";
import { useCharacterCustomization } from "../context/CharacterCustomization";

const Woman = (props) => {
  const group = React.useRef();
  const { scene, animations } = useGLTF("./models/woman.gltf");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions, names } = useAnimations(animations, group);
  const { setAnimations, animationIndex } = useAnimation();
  const {
    hairColor,
    eyeColor,
    mouthColor,
    glassColor,
    shirtColor,
    paintsColor,
    shoseColor,
    lacesColor,
    soleColor,
  } = useCharacterCustomization();

  useEffect(() => {
    setAnimations(names);
  }, [names]);

  useEffect(() => {
    actions[names[animationIndex]].reset().fadeIn(0.5).play();
    return () => actions[names[animationIndex]].fadeOut(0.5);
  }, [animationIndex]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <group name="SM_Chr_Developer_Female_02">
            <skinnedMesh
              castShadow
              name="Mesh019"
              geometry={nodes.Mesh019.geometry}
              skeleton={nodes.Mesh019.skeleton}
            >
              <meshStandardMaterial {...materials.Glasses} color={glassColor} />
            </skinnedMesh>
            <skinnedMesh
              castShadow
              name="Mesh019_1"
              geometry={nodes.Mesh019_1.geometry}
              skeleton={nodes.Mesh019_1.skeleton}
            >
              <meshStandardMaterial {...materials.Eyes} color={eyeColor} />
            </skinnedMesh>
            <skinnedMesh
              castShadow
              name="Mesh019_2"
              geometry={nodes.Mesh019_2.geometry}
              skeleton={nodes.Mesh019_2.skeleton}
            >
              <meshStandardMaterial {...materials.Hair} color={hairColor} />
            </skinnedMesh>
            <skinnedMesh
              castShadow
              name="Mesh019_3"
              geometry={nodes.Mesh019_3.geometry}
              material={materials.Skin}
              skeleton={nodes.Mesh019_3.skeleton}
            />
            <skinnedMesh
              castShadow
              name="Mesh019_4"
              geometry={nodes.Mesh019_4.geometry}
              material={materials.Mouth}
              skeleton={nodes.Mesh019_4.skeleton}
            >
              <meshStandardMaterial {...materials.Mouth} color={mouthColor} />
            </skinnedMesh>
            <skinnedMesh
              castShadow
              name="Mesh019_5"
              geometry={nodes.Mesh019_5.geometry}
              skeleton={nodes.Mesh019_5.skeleton}
            >
              <meshStandardMaterial {...materials.Shirt} color={shirtColor} />
            </skinnedMesh>
            <skinnedMesh
              castShadow
              name="Mesh019_6"
              geometry={nodes.Mesh019_6.geometry}
              skeleton={nodes.Mesh019_6.skeleton}
            >
              <meshStandardMaterial {...materials.Pants} color={paintsColor} />
            </skinnedMesh>
            <skinnedMesh
              castShadow
              name="Mesh019_7"
              geometry={nodes.Mesh019_7.geometry}
              skeleton={nodes.Mesh019_7.skeleton}
            >
              <meshStandardMaterial {...materials.Shoes} color={shoseColor} />
            </skinnedMesh>
            <skinnedMesh
              castShadow
              name="Mesh019_8"
              geometry={nodes.Mesh019_8.geometry}
              skeleton={nodes.Mesh019_8.skeleton}
            >
              <meshStandardMaterial {...materials.Sole} color={soleColor} />
            </skinnedMesh>
            <skinnedMesh
              castShadow
              name="Mesh019_9"
              geometry={nodes.Mesh019_9.geometry}
              skeleton={nodes.Mesh019_9.skeleton}
            >
              <meshStandardMaterial {...materials.Laces} color={lacesColor} />
            </skinnedMesh>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("./models/woman.gltf");

export default Woman;
